#!/usr/bin/env bash

set -eo pipefail

if [[ $# != 1 ]]; then
  echo "Usage: $0 <gem name>" >&2
  exit 1
fi

gemname=$1

bundle gem $gemname
cd $gemname

cat <<TRAVIS_YML > .travis.yml
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.1
  - 2.2
  - 2.3.3
before_install: gem install bundler -v $(bundle --version | awk '{print $3}')
script:
  - bundle exec rake
  - bash <(curl -fsSL https://github.com/everypolitician/ensure-regression-tests/raw/master/ensure-regression-tests)
TRAVIS_YML

rubocop --auto-correct --fail-level F --format s

cat <<RUBOCOP_YML > .rubocop.yml
AllCops:
  TargetRubyVersion: 2.1

inherit_from:
  - https://raw.githubusercontent.com/everypolitician/everypolitician-data/master/.rubocop_base.yml
RUBOCOP_YML

cat <<CHANGELOG > CHANGELOG.md
# Change Log

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](http://keepachangelog.com/)
and this project adheres to [Semantic Versioning](http://semver.org/).

## Unreleased

### Added

- Add notes about new features here.
CHANGELOG

git add .
git commit -m "Create $gemname with $(basename $0)"

echo

echo "Created $gemname in $(pwd)"

echo "Next steps:"
echo
echo "- [ ] Create $gemname repository on GitHub"
echo "- [ ] Install the Travis CI gem and run 'travis enable' from the root dir of the gem"
echo "- [ ] Fill out $gemname.gemspec"
