#!/usr/bin/env ruby
# frozen_string_literal: true
require 'thor'
require 'pathname'
require 'bundler'

module Everypolitician
  class Rubygem < Thor
    include Thor::Actions

    TEST_FRAMEWORK_VERSIONS = {
      'minitest' => '5.0'
    }.freeze

    def self.source_root
      File.expand_path(File.join(File.dirname(__FILE__), 'templates'))
    end

    desc 'new NAME', 'Create a new EveryPolitician RubyGem called NAME'
    def new(name)
      underscored_name = name.tr('-', '_')
      namespaced_path = name.tr('-', '/')
      constant_name = name.gsub(/-[_-]*(?![_-]|$)/) { '::' }.gsub(/([_-]+|(::)|^)(.|$)/) { Regexp.last_match(2).to_s + Regexp.last_match(3).upcase }
      constant_array = constant_name.split('::')

      target = Pathname.new(File.join(Dir.pwd, name))

      config = {
        name: name,
        underscored_name: underscored_name,
        namespaced_path: namespaced_path,
        constant_name: constant_name,
        constant_array: constant_array,
        author: 'EveryPolitician',
        email: 'team@everypolitician.org',
        bundler_version: bundler_dependency_version,
        git_user_name: 'everypolitician'
      }
      ensure_safe_gem_name(name, constant_array)

      templates = {
        'Gemfile.tt' => 'Gemfile',
        'gitignore.tt' => '.gitignore',
        'lib/newgem.rb.tt' => "lib/#{namespaced_path}.rb",
        'lib/newgem/version.rb.tt' => "lib/#{namespaced_path}/version.rb",
        'newgem.gemspec.tt' => "#{name}.gemspec",
        'Rakefile.tt' => 'Rakefile',
        'README.md.tt' => 'README.md',
        'bin/console.tt' => 'bin/console',
        'bin/setup.tt' => 'bin/setup'
      }

      executables = %w(
        bin/console
        bin/setup
      )

      config[:test] = 'minitest'
      config[:test_framework_version] = TEST_FRAMEWORK_VERSIONS['minitest']

      templates['.travis.yml.tt'] = '.travis.yml'

      templates['test/test_helper.rb.tt'] = 'test/test_helper.rb'
      templates['test/newgem_test.rb.tt'] = "test/#{namespaced_path}_test.rb"

      config[:test_task] = 'test'

      config[:mit] = true
      templates.merge!("LICENSE.txt.tt" => "LICENSE.txt")

      templates.each do |src, dst|
        template("newgem/#{src}", target.join(dst), config)
      end

      executables.each do |file|
        path = target.join(file)
        executable = (path.stat.mode | 0o111)
        path.chmod(executable)
      end

      warn "Initializing git repo in #{target}"
      Dir.chdir(target) do
        `git init`
        `git add .`
      end
    end

    private

    def resolve_name(name)
      SharedHelpers.pwd.join(name).basename.to_s
    end

    def bundler_dependency_version
      v = Gem::Version.new(Bundler::VERSION)
      req = v.segments[0..1]
      req << 'a' if v.prerelease?
      req.join('.')
    end

    def ensure_safe_gem_name(name, constant_array)
      if name =~ /^\d/
        warn "Invalid gem name #{name} Please give a name which does not start with numbers."
        exit 1
      elsif constant_array.inject(Object) { |c, s| (c.const_defined?(s) && c.const_get(s)) || break }
        warn "Invalid gem name #{name} constant #{constant_array.join('::')} is already in use. Please choose another gem name."
        exit 1
      end
    end
  end
end

Everypolitician::Rubygem.start(ARGV)
